/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge */

#ifndef _Included_dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge
#define _Included_dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge
 * Method:    nativeInitializeJvmPlant
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge_nativeInitializeJvmPlant
  (JNIEnv *, jclass);

/*
 * Class:     dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge
 * Method:    nativeGetClassFile
 * Signature: (Ljava/lang/Class;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge_nativeGetClassFile
  (JNIEnv *, jclass, jclass);

/*
 * Class:     dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge
 * Method:    nativeRedefineClassV2
 * Signature: (Ljava/lang/Class;[BZ)V
 */
JNIEXPORT void JNICALL Java_dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge_nativeRedefineClassV2
  (JNIEnv *, jclass, jclass, jbyteArray, jboolean);

/*
 * Class:     dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge
 * Method:    nativeGetClassInitializer
 * Signature: (Ljava/lang/Class;)Ljava/lang/reflect/Constructor;
 */
JNIEXPORT jobject JNICALL Java_dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge_nativeGetClassInitializer
  (JNIEnv *, jclass, jclass);

/*
 * Class:     dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge
 * Method:    nativeAllocateInstance
 * Signature: (Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge_nativeAllocateInstance
  (JNIEnv *, jclass, jclass);

/*
 * Class:     dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge
 * Method:    invokeNonVirtualArtMethodImpl
 * Signature: (Ljava/lang/reflect/Member;Ljava/lang/String;Ljava/lang/Class;ZLjava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_dev_tmpfs_jvmplant_impl_JvmPlantNativeBridge_invokeNonVirtualArtMethodImpl
  (JNIEnv *, jclass, jobject, jstring, jclass, jboolean, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
