//
// Created by sulfate on 2025-05-15.
//

#include "jvmti_error_strings.h"

#include <fmt/format.h>

namespace jvmplant {

std::string JvmtiErrorToSting(jvmtiError err) {
#define JVMTI_ERROR_STRING(name)                                                                                       \
    case name:                                                                                                         \
        return #name;

    switch (err) {
        JVMTI_ERROR_STRING(JVMTI_ERROR_INVALID_FIELDID)
        JVMTI_ERROR_STRING(JVMTI_ERROR_NO_MORE_FRAMES)
        JVMTI_ERROR_STRING(JVMTI_ERROR_OPAQUE_FRAME)
        JVMTI_ERROR_STRING(JVMTI_ERROR_TYPE_MISMATCH)
        JVMTI_ERROR_STRING(JVMTI_ERROR_INVALID_SLOT)
        JVMTI_ERROR_STRING(JVMTI_ERROR_DUPLICATE)
        JVMTI_ERROR_STRING(JVMTI_ERROR_NOT_FOUND)
        JVMTI_ERROR_STRING(JVMTI_ERROR_INVALID_MONITOR)
        JVMTI_ERROR_STRING(JVMTI_ERROR_NOT_MONITOR_OWNER)
        JVMTI_ERROR_STRING(JVMTI_ERROR_INTERRUPT)
        JVMTI_ERROR_STRING(JVMTI_ERROR_INVALID_CLASS_FORMAT)
        JVMTI_ERROR_STRING(JVMTI_ERROR_CIRCULAR_CLASS_DEFINITION)
        JVMTI_ERROR_STRING(JVMTI_ERROR_FAILS_VERIFICATION)
        JVMTI_ERROR_STRING(JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_ADDED)
        JVMTI_ERROR_STRING(JVMTI_ERROR_UNSUPPORTED_REDEFINITION_SCHEMA_CHANGED)
        JVMTI_ERROR_STRING(JVMTI_ERROR_INVALID_TYPESTATE)
        JVMTI_ERROR_STRING(JVMTI_ERROR_UNSUPPORTED_REDEFINITION_HIERARCHY_CHANGED)
        JVMTI_ERROR_STRING(JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_DELETED)
        JVMTI_ERROR_STRING(JVMTI_ERROR_UNSUPPORTED_VERSION)
        JVMTI_ERROR_STRING(JVMTI_ERROR_NAMES_DONT_MATCH)
        JVMTI_ERROR_STRING(JVMTI_ERROR_UNSUPPORTED_REDEFINITION_CLASS_MODIFIERS_CHANGED)
        JVMTI_ERROR_STRING(JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_MODIFIERS_CHANGED)
        JVMTI_ERROR_STRING(JVMTI_ERROR_UNMODIFIABLE_CLASS)
        JVMTI_ERROR_STRING(JVMTI_ERROR_NOT_AVAILABLE)
        JVMTI_ERROR_STRING(JVMTI_ERROR_MUST_POSSESS_CAPABILITY)
        JVMTI_ERROR_STRING(JVMTI_ERROR_NULL_POINTER)
        JVMTI_ERROR_STRING(JVMTI_ERROR_ABSENT_INFORMATION)
        JVMTI_ERROR_STRING(JVMTI_ERROR_INVALID_EVENT_TYPE)
        JVMTI_ERROR_STRING(JVMTI_ERROR_ILLEGAL_ARGUMENT)
        JVMTI_ERROR_STRING(JVMTI_ERROR_NATIVE_METHOD)
        JVMTI_ERROR_STRING(JVMTI_ERROR_CLASS_LOADER_UNSUPPORTED)
        JVMTI_ERROR_STRING(JVMTI_ERROR_OUT_OF_MEMORY)
        JVMTI_ERROR_STRING(JVMTI_ERROR_ACCESS_DENIED)
        JVMTI_ERROR_STRING(JVMTI_ERROR_WRONG_PHASE)
        JVMTI_ERROR_STRING(JVMTI_ERROR_INTERNAL)
        JVMTI_ERROR_STRING(JVMTI_ERROR_UNATTACHED_THREAD)
        JVMTI_ERROR_STRING(JVMTI_ERROR_INVALID_ENVIRONMENT)

#undef JVMTI_ERROR_STRING

        default:
            return fmt::format("(jvmtiError: {})", static_cast<int>(err));
    }
}

} // namespace jvmplant
