[versions]
log4j = "2.23.1"

[libraries]
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.1" }

[plugins]
