name: main

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'renovate.json'
      - '.editorconfig'
      - '.gitignore'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:
    name: Build CI (Push)
    runs-on: ubuntu-24.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_BASEDIR: "${{ github.workspace }}"
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Config submodules
        run: |
          git submodule foreach git submodule update --init --recursive

      - name: Build Native Libs
        run: |
          mkdir -p native/build && cmake -S native -B native/build && make -C native/build jvmplant -j 4
          echo "NATIVE_LIB_BUILD_DIR=$(realpath native/build)" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0

      - name: Build with Gradle
        run: |
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          sed -i 's/org.gradle.configuration-cache=true//g' gradle.properties
          echo 'buildCache { local { removeUnusedEntriesAfterDays = 1 } }' >> settings.gradle.kts
          ./gradlew :jvm:core:assemble :jvm:xposed:assemble

      - name: Run tests
        run: |
          ./gradlew :jvm:test:test --tests "dev.tmpfs.jvmplant.test.HookTests"
        env:
          JVMPLANT_TEST_NATIVE_DIR: ${{ env.NATIVE_LIB_BUILD_DIR }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            jvm/**/build/libs/*.jar
            native/build/*.so
            native/build/*.dll
            native/build/*.a
            native/build/*.dylib
          name: JvmXposed-linux-x86_64-${{ github.event.head_commit.id }}
